name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install flake8

      - name: Lint Python code
        run: |
          # Lint Python files
          flake8 .

  deploy_lambda:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy Lambda Function
        run: |
          # Replace with your AWS CLI commands to deploy Lambda function using Terraform
          terraform init
          terraform apply -auto-approve
